---
- name: "Start network.vpn.run"
  ansible.builtin.debug:
    msg: "Starting ansible.vpn.run"

- name: "Load and run specified actions"
  ansible.builtin.include_tasks: "{{ item.name }}.yaml"
  loop: "{{ actions }}"
